UPDATE product SET description = 'iPhone 15 128GB 黑色款，几乎全新，无划痕无维修，配件齐全含原装充电线，支持官方验机。' WHERE id = 1;
UPDATE product SET description = 'MacBook Pro 14英寸 M3芯片 2024款，8GB内存 512GB固态硬盘，几乎全新仅开机几次，电池循环个位数。' WHERE id = 2;
UPDATE product SET description = '《深入理解计算机系统》CSAPP第三版英文原版，经典计算机教材，轻微荧光笔标记仅前两章，其余全新。' WHERE id = 3;
UPDATE product SET description = 'Nike Air Jordan 1 Retro Bred经典黑红配色，42码，仅穿过三次几乎无磨损，原装鞋盒齐全，正品保证。' WHERE id = 4;
UPDATE product SET description = '小米智能台灯Pro，支持语音控制及2700K-6500K色温调节，几乎全新使用不到一个月，包装配件齐全。' WHERE id = 5;
UPDATE product SET description = 'Wilson Evolution室内篮球，官方7号比赛用球，使用一季手感依然出色，表面纹路清晰气密性完好。' WHERE id = 6;
UPDATE product SET description = '香奈儿Chanel No.5 EDP淡香精100ml，经典花香调仅喷两三次余量95%以上，包装盒齐全正品保证。' WHERE id = 7;
UPDATE product SET description = 'Bugaboo Bee6婴儿推车，轻量折叠款使用半年，车架完好推行顺滑，含雨罩和原装配件已清洁。' WHERE id = 8;
UPDATE product SET description = 'iPad Air M2芯片11英寸128GB WiFi版，2024年新款几乎未使用，已贴钢化膜，包装配件齐全。' WHERE id = 9;
UPDATE product SET description = '索尼WH-1000XM5头戴式降噪耳机，行业领先主动降噪续航30小时，几乎全新成色无磕碰。' WHERE id = 10;
UPDATE product SET description = '三星Galaxy S24 Ultra 256GB钛灰色，国行正品激活不到一个月，配件齐全含原装快充。' WHERE id = 11;
UPDATE product SET description = 'The North Face 1996 Retro Nuptse羽绒夹克，经典黑色L码仅穿一季，保存完好蓬松度依然好。' WHERE id = 12;
UPDATE product SET description = 'Gucci GG Marmont小号链条单肩包，经典双G logo几乎全新只背几次，防尘袋包装盒齐全。' WHERE id = 13;
UPDATE product SET description = '《代码整洁之道》Clean Code英文原版，软件工程经典必读，几乎全新无标记封面完好。' WHERE id = 14;
UPDATE product SET description = '《设计模式》GoF经典之作英文原版，几乎全新无翻折，收藏级品相。' WHERE id = 15;
UPDATE product SET description = '戴森Dyson V15 Detect无线吸尘器，激光探测微尘吸力强劲，几乎全新配件齐全含多个吸头。' WHERE id = 16;
UPDATE product SET description = 'MUJI无印良品大号香薰机，简约设计静音运行，几乎全新只加两次精油，包装说明书齐全。' WHERE id = 17;
UPDATE product SET description = '佳明Garmin Forerunner 265跑步手表，AMOLED屏几乎全新，心率GPS精准续航出色。' WHERE id = 18;
UPDATE product SET description = 'Lululemon Align高腰紧身运动裤，黑色S码Nulu面料柔软亲肤，几乎全新只穿两次弹性完好。' WHERE id = 19;
UPDATE product SET description = 'SK-II神仙水护肤精华露230ml，经典Pitera酵母精华，几乎全新只用几次日期新鲜包装齐全。' WHERE id = 20;
UPDATE product SET description = '戴森Dyson Airwrap多功能美发造型器全套，几乎全新只用几次，所有风嘴齐全包装完好。' WHERE id = 21;
UPDATE product SET description = 'Stokke Tripp Trapp成长椅，经典设计伴随成长，几乎全新只用不到四个月无划痕配件齐全。' WHERE id = 22;
UPDATE product SET description = '乐高LEGO DUPLO得宝系列卡车和挖掘机套装，几乎全新只玩几次颗粒齐全无缺失带原包装盒。' WHERE id = 23;
UPDATE product SET description = 'AirPods Pro 2 USB-C版本，主动降噪功能完美续航正常，配件齐全含耳塞和充电线。' WHERE id = 24;
UPDATE product SET description = '佳能EOS R6 Mark II机身，快门数不到5000传感器干净，包装保修卡齐全送原装电池一块。' WHERE id = 25;
UPDATE product SET description = '罗技MX Master 3S无线鼠标，静音按键几乎全新仅使用一周，包装盒和接收器齐全。' WHERE id = 26;
UPDATE product SET description = '三星990 Pro 2TB NVMe固态硬盘，PCIe 4.0接口读写超快，通电时间不到100小时包装齐全。' WHERE id = 27;
UPDATE product SET description = 'Apple Watch Ultra 2高山回环表带款，几乎全新无划痕续航正常，包装充电器齐全AC+在保。' WHERE id = 28;
UPDATE product SET description = 'Keychron Q1 Pro客制化机械键盘，佳达隆红轴铝制外壳，几乎全新只打几次字配件齐全。' WHERE id = 29;
UPDATE product SET description = '大疆DJI Mini 4 Pro无人机带屏遥控器版，飞行不到5小时无炸机无维修，包装配件齐全。' WHERE id = 30;
UPDATE product SET description = 'Kindle Paperwhite 5第11代32GB大容量，几乎全新只看两本书屏幕完好，包装齐全。' WHERE id = 31;
UPDATE product SET description = '三星34英寸Odyssey G5超宽曲面显示器，2K分辨率165Hz几乎全新无坏点，包装底座齐全。' WHERE id = 32;
UPDATE product SET description = '安克PowerHouse 767户外移动电源2048Wh，用过两次露营成色新净，配件齐全。' WHERE id = 33;
UPDATE product SET description = '雷蛇DeathAdder V3 Pro电竞鼠标，超轻量设计几乎全新仅测试手感，包装接收器齐全。' WHERE id = 34;
UPDATE product SET description = '富士X100VI数码相机4020万像素，几乎全新快门不到1000屏幕已贴膜，包装配件齐全。' WHERE id = 35;
UPDATE product SET description = 'Nothing Phone (2) 256GB白色款，国行正品激活两个月几乎全新无划痕，包装充电器齐全。' WHERE id = 36;
UPDATE product SET description = '华硕ROG Ally掌上游戏机Z1 Extreme芯片，几乎全新只玩几个游戏带贴膜保护壳包装齐全。' WHERE id = 37;
UPDATE product SET description = 'LG 27英寸UltraFine 5K显示器苹果推荐款，几乎全新无坏点划痕色彩完美，包装底座齐全。' WHERE id = 38;
UPDATE product SET description = 'Elgato Stream Deck MK.2直播控制台，几乎全新只调试一次按键灵敏，包装数据线齐全。' WHERE id = 39;
UPDATE product SET description = '群晖DS224+双盘位NAS，几乎全新只用不到一个月无硬盘版本，包装电源适配器齐全。' WHERE id = 40;
UPDATE product SET description = 'Marshall Stanmore III蓝牙音箱，经典摇滚外观音质出色，几乎全新无磕碰包装配件齐全。' WHERE id = 41;
UPDATE product SET description = '优衣库Ultra Light Down超轻羽绒马甲，黑色M码几乎全新只穿两次，轻便保暖适合春秋。' WHERE id = 42;
UPDATE product SET description = '阿迪达斯Ultraboost 23跑步鞋白色男款43码，Boost科技缓震极佳，仅穿一周鞋底几乎无磨损。' WHERE id = 43;
UPDATE product SET description = 'ZARA双面羊毛大衣灰色L码，含毛量高保暖性好，仅穿一季干洗一次版型经典百搭。' WHERE id = 44;
UPDATE product SET description = '匡威Chuck 70 Hi帆布鞋经典黑高帮42码，几乎全新仅穿两天鞋底干净无磨损，包装盒齐全。' WHERE id = 45;
UPDATE product SET description = 'Patagonia Better Sweater摇粒绒外套深蓝色M码，环保面料柔软保暖，穿着舒适保存完好。' WHERE id = 46;
UPDATE product SET description = 'Nike Air Force 1纯白经典款42码，几乎全新只穿一周鞋面干净无泛黄，包装盒齐全。' WHERE id = 47;
UPDATE product SET description = 'COS Oversized纯棉衬衫白色L码宽松版型，面料质感极佳几乎全新只穿一次，设计简约百搭。' WHERE id = 48;
UPDATE product SET description = 'New Balance 990v6灰色老爹鞋美产经典款43码，几乎全新穿着不到五次鞋底纹路清晰。' WHERE id = 49;
UPDATE product SET description = 'Weekday Astro Loose宽松牛仔裤深蓝色32码，直筒版型面料厚实，几乎全新只穿一次已水洗。' WHERE id = 50;
UPDATE product SET description = 'Carhartt WIP Detroit工装夹克经典卡其色M码，硬挺有型穿着不到一季，保存完好无破损。' WHERE id = 51;
UPDATE product SET description = 'Hoka One One Bondi 8缓震跑鞋黑色男款43码，超厚底柔软舒适，仅穿一周通勤使用。' WHERE id = 52;
UPDATE product SET description = 'A.P.C. Petit New Standard修身牛仔裤原色未水洗30码，日本丹宁面料仅试穿几乎全新。' WHERE id = 53;
UPDATE product SET description = 'Salomon XT-6 Gore-Tex防水越野鞋灰色42.5码，户外神鞋几乎全新仅穿两次防水性能完好。' WHERE id = 54;
UPDATE product SET description = '始祖鸟Arcteryx Atom LT连帽棉服黑色L码，轻量保暖几乎全新户外神器，保存完好。' WHERE id = 55;
UPDATE product SET description = 'Champion Reverse Weave加绒卫衣灰色L码经典款，面料厚实穿着舒适，保存完好无明显磨损。' WHERE id = 56;
UPDATE product SET description = '《程序员修炼之道》20周年纪念版，经典软件开发指南更新版，几乎全新仅翻看一遍无标记。' WHERE id = 57;
UPDATE product SET description = '《算法导论》第4版英文原版，计算机算法圣经级教材，几乎全新无标记封面略有折痕。' WHERE id = 58;
UPDATE product SET description = '《重构》第2版Martin Fowler著，软件工程经典JavaScript示例版，几乎全新无翻折标记。' WHERE id = 59;
UPDATE product SET description = '《深度学习》Goodfellow和Bengio著，AI领域必读经典，几乎全新无标记硬壳精装版。' WHERE id = 60;
UPDATE product SET description = '《人类简史》Sapiens英文原版，全球畅销历史科普读物，几乎全新只读一遍无折角标记。' WHERE id = 61;
UPDATE product SET description = '《原子习惯》Atomic Habits英文原版，习惯养成类畅销书第一名，几乎全新无标记封面完美。' WHERE id = 62;
UPDATE product SET description = '《数据库内幕》Database Internals，深入理解数据库底层原理，几乎全新仅翻阅一遍。' WHERE id = 63;
UPDATE product SET description = '《构建微服务》第2版，微服务架构设计权威指南，几乎全新无标记技术人必备参考书。' WHERE id = 64;
UPDATE product SET description = '《Kubernetes入门与实战》第3版，云原生时代必读，几乎全新无折角内容详实实用。' WHERE id = 65;
UPDATE product SET description = '《软件架构基础》Fundamentals of Software Architecture，几乎全新无标记架构师必备参考。' WHERE id = 66;
UPDATE product SET description = '《计算机网络：自顶向下方法》第8版英文原版，网络领域经典教材几乎全新无标记。' WHERE id = 67;
UPDATE product SET description = '《操作系统概念》第10版英文原版，OS领域权威教材，几乎全新仅翻阅前几章。' WHERE id = 68;
UPDATE product SET description = '《SRE：Google运维解密》英文原版，DevOps和SRE领域必读书，几乎全新无标记。' WHERE id = 69;
UPDATE product SET description = '《纳瓦尔宝典》The Almanack of Naval Ravikant，智慧箴言集几乎全新，值得反复阅读。' WHERE id = 70;
UPDATE product SET description = '《系统设计面试》第2卷，大厂面试必备参考，几乎全新无标记内容实用含大量案例。' WHERE id = 71;
UPDATE product SET description = '飞利浦Hue White Ambiance智能灯泡入门套装，含桥接器和3个灯泡，几乎全新已重置包装齐全。' WHERE id = 72;
UPDATE product SET description = 'Nespresso Vertuo Next胶囊咖啡机，几乎全新制作不到50杯清洁干净包装齐全，送剩余胶囊。' WHERE id = 73;
UPDATE product SET description = '宜家IKEA KALLAX格子柜4x4白色，几乎全新无磕碰已组装可直接使用，承重稳固。' WHERE id = 74;
UPDATE product SET description = '博世Bosch Serie 4嵌入式洗碗机60cm款，几乎全新使用不到半年洗涤效果出色说明书齐全。' WHERE id = 75;
UPDATE product SET description = 'Le Creuset珐琅铸铁荷兰锅24cm樱桃红，几乎全新只炖几次汤无磕碰无裂纹，附原装包装。' WHERE id = 76;
UPDATE product SET description = 'iRobot Roomba j7+扫地机器人带自动集尘底座，几乎全新使用两个月地图已重置配件齐全。' WHERE id = 77;
UPDATE product SET description = 'Vitamix A3500破壁料理机旗舰款，几乎全新只打几次果汁刀片锋利马达强劲，包装配件齐全。' WHERE id = 78;
UPDATE product SET description = '象印Zojirushi NS-TSC10微电脑电饭煲5.5杯容量，几乎全新只用十几次内胆无划痕。' WHERE id = 79;
UPDATE product SET description = 'Tempur-Pedic泰普尔Symphony护颈枕头Queen尺寸，几乎全新只枕一周不习惯带原装枕套。' WHERE id = 80;
UPDATE product SET description = 'Ruggable Kamran波西米亚风格可机洗地毯8x10英尺，几乎全新无污渍已清洗干净随时可用。' WHERE id = 81;
UPDATE product SET description = '双立人Zwilling Pro 7件套刀具套装，几乎全新只用其中两把刀刃锋利无缺口刀架齐全。' WHERE id = 82;
UPDATE product SET description = 'Herman Miller Aeron人体工学椅Size B，几乎全新只坐不到三个月腰部支撑完美正品好货。' WHERE id = 83;
UPDATE product SET description = '三星AX90空气净化器90平米适用，几乎全新滤网剩余90%以上静音效果好，包装说明书齐全。' WHERE id = 84;
UPDATE product SET description = 'Instant Pot Duo Plus 6夸脱9合1多功能锅，几乎全新只用五次内胆无划痕，配件密封圈齐全。' WHERE id = 85;
UPDATE product SET description = '雅马哈YDP-165电钢琴含琴凳，几乎全新弹奏不到50小时音色优美手感出色，包装说明书齐全。' WHERE id = 86;
UPDATE product SET description = 'Manduka PRO瑜伽垫6mm黑色，专业级瑜伽垫几乎全新只用不到十次，防滑耐用无异味。' WHERE id = 87;
UPDATE product SET description = 'Concept2 Model D PM5划船机，健身房同款几乎全新使用不到50小时运转流畅静音配件齐全。' WHERE id = 88;
UPDATE product SET description = 'Osprey Atmos AG 65男款登山背包，反重力背负系统舒适透气，几乎全新只背两趟短途。' WHERE id = 89;
UPDATE product SET description = 'PowerBlock Elite EXP可调节哑铃单只5-50磅，几乎全新使用不到一个月设计紧凑省空间。' WHERE id = 90;
UPDATE product SET description = 'Brooks Ghost 16缓震跑鞋男款44码，几乎全新仅跑不到50公里鞋底磨损极少回弹出色。' WHERE id = 91;
UPDATE product SET description = 'Yeti SB140 T3全避震山地车L码，几乎全新骑行不到200公里XT套件Fox避震车况完美。' WHERE id = 92;
UPDATE product SET description = '佳明Garmin Edge 840 Solar太阳能码表，几乎全新只用三次骑行屏幕完美GPS精准。' WHERE id = 93;
UPDATE product SET description = 'Peak Design碳纤维旅行三脚架，轻量便携几乎全新只用两次承重稳固，收纳包齐全。' WHERE id = 94;
UPDATE product SET description = 'Patagonia Black Hole Duffel 55L防水行李袋，几乎全新只用一次短途防水耐磨无破损。' WHERE id = 95;
UPDATE product SET description = 'Rapha Pro Team长袖骑行服深蓝色L码，专业竞赛级针织面料，几乎全新只穿两次训练。' WHERE id = 96;
UPDATE product SET description = 'Black Diamond Spot 400-R头灯400流明，几乎全新只用两次夜爬防水防尘续航长。' WHERE id = 97;
UPDATE product SET description = 'Shimano Ultegra R8000公路车套件11速，几乎全新使用不到500公里变速精准刹车灵敏。' WHERE id = 98;
UPDATE product SET description = 'Hydro Flask宽口保温杯32oz，几乎全新只用两周保温24h保冷48h，无磕碰掉漆。' WHERE id = 99;
UPDATE product SET description = 'Titleist Pro V1高尔夫球3打球装，全新未拆封2024年产，手感出色适合中低差点球手。' WHERE id = 100;
UPDATE product SET description = '海蓝之谜La Mer经典面霜60ml传奇修复力，几乎全新只用不到五次，包装盒小勺齐全正品保证。' WHERE id = 101;
UPDATE product SET description = 'Tom Ford Oud Wood乌木沉香EDP 50ml，高级木质香调几乎全新仅喷几次，包装盒齐全正品。' WHERE id = 102;
UPDATE product SET description = 'Olaplex No.3头发修复精华100ml，几乎全新只用一次发量少用不完，包装齐全日期新鲜。' WHERE id = 103;
UPDATE product SET description = 'Jo Malone祖玛珑英国梨与小苍兰100ml，几乎全新余量90%以上，包装齐全正品。' WHERE id = 104;
UPDATE product SET description = 'Augustinus Bader The Rich Cream德国AB蓝面霜50ml，贵妇级抗老几乎全新包装盒齐全。' WHERE id = 105;
UPDATE product SET description = 'Byredo Gypsy Water流浪者之歌EDP 50ml，小众高级香几乎全新仅试香，包装齐全正品保证。' WHERE id = 106;
UPDATE product SET description = 'Drunk Elephant C-Firma维C日间精华，几乎全新只用三次日期新鲜在有效期内，包装齐全。' WHERE id = 107;
UPDATE product SET description = 'Aesop伊索Resurrection复活芳香护手霜，几乎全新只用几次柑橘木质调香味高级包装完好。' WHERE id = 108;
UPDATE product SET description = '资生堂Shiseido红腰子精华75ml，几乎全新只用不到十分之一，日期新鲜包装齐全。' WHERE id = 109;
UPDATE product SET description = 'Charlotte Tilbury Pillow Talk枕边话口红，几乎全新仅试色一次热门色号，正品保证。' WHERE id = 110;
UPDATE product SET description = 'Tatcha The Dewy Skin Cream水润面霜50ml，日系高端护肤几乎全新只用不到五次包装盒齐全。' WHERE id = 111;
UPDATE product SET description = 'NARS光亮柔滑遮瑕膏Custard色号，几乎全新仅试用遮盖力好不卡纹，正品包装齐全。' WHERE id = 112;
UPDATE product SET description = 'Diptyque蒂普提克Baies浆果香氛蜡烛190g，几乎全新只点不到两小时香味高级扩散好。' WHERE id = 113;
UPDATE product SET description = 'Sunday Riley Good Genes乳酸焕肤精华30ml，几乎全新只用一次耐受不适，日期新鲜包装齐全。' WHERE id = 114;
UPDATE product SET description = 'Clarisonic Mia Smart超声波洁面仪，几乎全新充几次电刷头全新未使用，包装充电器齐全。' WHERE id = 115;
UPDATE product SET description = 'UPPAbaby VISTA V2高景观婴儿推车Gregory蓝，几乎全新用不到半年含睡篮和安全提篮适配器。' WHERE id = 116;
UPDATE product SET description = 'Nuna RAVA儿童安全座椅Caviar黑色，几乎全新只用不到三个月无事故无异味ISOFIX稳固。' WHERE id = 117;
UPDATE product SET description = 'BabyBjorn婴儿摇椅Balance Soft灰色网面款，几乎全新用不到半年面料可拆洗无污渍。' WHERE id = 118;
UPDATE product SET description = 'Hatch Rest婴儿助眠灯白噪音夜灯，几乎全新功能完好APP控制方便，包装配件齐全。' WHERE id = 119;
UPDATE product SET description = 'Lovevery早教玩具套装The Senser 5-6月龄，几乎全新只玩几次已消毒清洁所有配件齐全。' WHERE id = 120;
UPDATE product SET description = 'Babyzen YOYO2轻便婴儿推车6月以上款，几乎全新用不到半年收折方便可登机已清洁。' WHERE id = 121;
UPDATE product SET description = 'Ergobaby Omni 360婴儿背带珍珠灰，几乎全新只用不到三个月透气网面舒适无变形。' WHERE id = 122;
UPDATE product SET description = '4moms mamaRoo 5多功能婴儿摇椅五种摇摆模式，几乎全新用不到半年面料可拆洗已清洁。' WHERE id = 123;
UPDATE product SET description = 'Magna-Tiles磁性积木透明色100片套装，几乎全新只玩几次磁性完好无破损带原装收纳盒。' WHERE id = 124;
UPDATE product SET description = 'Skip Hop婴儿三阶段活动中心，几乎全新只用不到半年桌面干净无污渍所有配件功能正常。' WHERE id = 125;
UPDATE product SET description = 'Britax B-Safe Gen2婴儿提篮式安全座椅黑色，几乎全新只用不到三个月无事故面料可拆洗。' WHERE id = 126;
UPDATE product SET description = 'Graco SimpleSwitch多功能儿童餐椅白灰色，几乎全新用不到四个月坐垫可拆洗无污渍。' WHERE id = 127;
UPDATE product SET description = 'Kyte BABY竹纤维婴儿睡袋1.0 TOG鼠尾草绿，几乎全新只用几次已清洗面料柔软亲肤。' WHERE id = 128;
UPDATE product SET description = 'Melissa & Doug木质仿真玩具厨房套装，几乎全新玩几次做工精致安全环保所有配件齐全。' WHERE id = 129;
UPDATE product SET description = 'Fisher-Price费雪Kick & Play钢琴健身毯，宝宝经典玩具几乎全新，音乐灯光功能完好已清洁。' WHERE id = 130;
