UPDATE product SET title = 'iPhone 15 128GB 黑色' WHERE id = 1;
UPDATE product SET title = 'MacBook Pro 14英寸 M3芯片 2024款' WHERE id = 2;
UPDATE product SET title = '深入理解计算机系统 CSAPP 第三版' WHERE id = 3;
UPDATE product SET title = 'Nike Air Jordan 1 黑红经典款' WHERE id = 4;
UPDATE product SET title = '小米智能台灯 Pro' WHERE id = 5;
UPDATE product SET title = 'Wilson Evolution 室内篮球' WHERE id = 6;
UPDATE product SET title = '香奈儿 No.5 EDP 淡香精 100ml' WHERE id = 7;
UPDATE product SET title = 'Bugaboo Bee6 婴儿推车' WHERE id = 8;
UPDATE product SET title = 'iPad Air M2芯片 11英寸 128GB WiFi版' WHERE id = 9;
UPDATE product SET title = '索尼 WH-1000XM5 头戴式降噪耳机' WHERE id = 10;
UPDATE product SET title = '三星 Galaxy S24 Ultra 256GB 钛灰色' WHERE id = 11;
UPDATE product SET title = '北面 1996 Retro Nuptse 羽绒夹克 黑色L码' WHERE id = 12;
UPDATE product SET title = 'Gucci GG Marmont 小号链条单肩包' WHERE id = 13;
UPDATE product SET title = '代码整洁之道 Clean Code 英文原版' WHERE id = 14;
UPDATE product SET title = '设计模式 GoF经典 英文原版' WHERE id = 15;
UPDATE product SET title = '戴森 V15 Detect 无线吸尘器' WHERE id = 16;
UPDATE product SET title = 'MUJI无印良品 大号香薰机' WHERE id = 17;
UPDATE product SET title = '佳明 Garmin Forerunner 265 跑步手表' WHERE id = 18;
UPDATE product SET title = 'Lululemon Align 高腰紧身运动裤 黑色S码' WHERE id = 19;
UPDATE product SET title = 'SK-II 神仙水 护肤精华露 230ml' WHERE id = 20;
UPDATE product SET title = '戴森 Airwrap 多功能美发造型器 全套' WHERE id = 21;
UPDATE product SET title = 'Stokke Tripp Trapp 成长椅' WHERE id = 22;
UPDATE product SET title = '乐高 DUPLO 得宝卡车挖掘机套装' WHERE id = 23;
UPDATE product SET title = 'AirPods Pro 2 USB-C版' WHERE id = 24;
UPDATE product SET title = '佳能 EOS R6 Mark II 机身' WHERE id = 25;
UPDATE product SET title = '罗技 MX Master 3S 无线鼠标' WHERE id = 26;
UPDATE product SET title = '三星 990 Pro 2TB NVMe 固态硬盘' WHERE id = 27;
UPDATE product SET title = 'Apple Watch Ultra 2 高山回环表带款' WHERE id = 28;
UPDATE product SET title = 'Keychron Q1 Pro 客制化机械键盘 佳达隆红轴' WHERE id = 29;
UPDATE product SET title = '大疆 DJI Mini 4 Pro 无人机 带屏遥控器版' WHERE id = 30;
UPDATE product SET title = 'Kindle Paperwhite 5 第11代 32GB' WHERE id = 31;
UPDATE product SET title = '三星 34英寸 Odyssey G5 超宽曲面显示器' WHERE id = 32;
UPDATE product SET title = '安克 PowerHouse 767 户外移动电源 2048Wh' WHERE id = 33;
UPDATE product SET title = '雷蛇 DeathAdder V3 Pro 电竞鼠标' WHERE id = 34;
UPDATE product SET title = '富士 X100VI 数码相机' WHERE id = 35;
UPDATE product SET title = 'Nothing Phone (2) 256GB 白色' WHERE id = 36;
UPDATE product SET title = '华硕 ROG Ally 掌上游戏机 Z1 Extreme' WHERE id = 37;
UPDATE product SET title = 'LG 27英寸 UltraFine 5K 显示器' WHERE id = 38;
UPDATE product SET title = 'Elgato Stream Deck MK.2 直播控制台' WHERE id = 39;
UPDATE product SET title = '群晖 DS224+ 双盘位NAS' WHERE id = 40;
UPDATE product SET title = 'Marshall Stanmore III 蓝牙音箱' WHERE id = 41;
UPDATE product SET title = '优衣库 超轻羽绒马甲 黑色M码' WHERE id = 42;
UPDATE product SET title = '阿迪达斯 Ultraboost 23 跑步鞋 白色43码' WHERE id = 43;
UPDATE product SET title = 'ZARA 双面羊毛大衣 灰色L码' WHERE id = 44;
UPDATE product SET title = '匡威 Chuck 70 Hi 高帮帆布鞋 黑色42码' WHERE id = 45;
UPDATE product SET title = 'Patagonia Better Sweater 摇粒绒外套 深蓝色M码' WHERE id = 46;
UPDATE product SET title = 'Nike Air Force 1 纯白经典款 42码' WHERE id = 47;
UPDATE product SET title = 'COS 宽松纯棉衬衫 白色L码' WHERE id = 48;
UPDATE product SET title = 'New Balance 990v6 灰色老爹鞋 43码' WHERE id = 49;
UPDATE product SET title = 'Weekday Astro Loose 宽松牛仔裤 深蓝色32码' WHERE id = 50;
UPDATE product SET title = 'Carhartt WIP Detroit 工装夹克 卡其色M码' WHERE id = 51;
UPDATE product SET title = 'Hoka One One Bondi 8 缓震跑鞋 黑色43码' WHERE id = 52;
UPDATE product SET title = 'A.P.C. Petit New Standard 修身牛仔裤 原色30码' WHERE id = 53;
UPDATE product SET title = 'Salomon XT-6 Gore-Tex 防水越野鞋 灰色42.5码' WHERE id = 54;
UPDATE product SET title = '始祖鸟 Atom LT 连帽棉服 黑色L码' WHERE id = 55;
UPDATE product SET title = 'Champion Reverse Weave 加绒卫衣 灰色L码' WHERE id = 56;
UPDATE product SET title = '程序员修炼之道 20周年纪念版' WHERE id = 57;
UPDATE product SET title = '算法导论 第4版 英文原版' WHERE id = 58;
UPDATE product SET title = '重构 第2版 Martin Fowler著' WHERE id = 59;
UPDATE product SET title = '深度学习 精装版 Goodfellow著' WHERE id = 60;
UPDATE product SET title = '人类简史 Sapiens 英文原版' WHERE id = 61;
UPDATE product SET title = '原子习惯 Atomic Habits 英文原版' WHERE id = 62;
UPDATE product SET title = '数据库内幕 Database Internals' WHERE id = 63;
UPDATE product SET title = '构建微服务 第2版' WHERE id = 64;
UPDATE product SET title = 'Kubernetes入门与实战 第3版' WHERE id = 65;
UPDATE product SET title = '软件架构基础' WHERE id = 66;
UPDATE product SET title = '计算机网络 自顶向下方法 第8版' WHERE id = 67;
UPDATE product SET title = '操作系统概念 第10版 英文原版' WHERE id = 68;
UPDATE product SET title = 'SRE Google运维解密 英文原版' WHERE id = 69;
UPDATE product SET title = '纳瓦尔宝典 The Almanack of Naval Ravikant' WHERE id = 70;
UPDATE product SET title = '系统设计面试 第2卷' WHERE id = 71;
UPDATE product SET title = '飞利浦 Hue 智能灯泡入门套装' WHERE id = 72;
UPDATE product SET title = 'Nespresso Vertuo Next 胶囊咖啡机' WHERE id = 73;
UPDATE product SET title = '宜家 KALLAX 格子柜 4x4 白色' WHERE id = 74;
UPDATE product SET title = '博世 Serie 4 嵌入式洗碗机 60cm' WHERE id = 75;
UPDATE product SET title = 'Le Creuset 珐琅铸铁荷兰锅 24cm 樱桃红' WHERE id = 76;
UPDATE product SET title = 'iRobot Roomba j7+ 扫地机器人 带自动集尘底座' WHERE id = 77;
UPDATE product SET title = 'Vitamix A3500 破壁料理机' WHERE id = 78;
UPDATE product SET title = '象印 微电脑电饭煲 5.5杯容量' WHERE id = 79;
UPDATE product SET title = '泰普尔 Symphony 护颈枕头 Queen尺寸' WHERE id = 80;
UPDATE product SET title = 'Ruggable Kamran 可机洗地毯 波西米亚风 8x10英尺' WHERE id = 81;
UPDATE product SET title = '双立人 Zwilling Pro 7件套刀具' WHERE id = 82;
UPDATE product SET title = 'Herman Miller Aeron 人体工学椅 Size B' WHERE id = 83;
UPDATE product SET title = '三星 AX90 空气净化器 90平米适用' WHERE id = 84;
UPDATE product SET title = 'Instant Pot Duo Plus 9合1多功能锅 6夸脱' WHERE id = 85;
UPDATE product SET title = '雅马哈 YDP-165 电钢琴 含琴凳' WHERE id = 86;
UPDATE product SET title = 'Manduka PRO 瑜伽垫 6mm 黑色' WHERE id = 87;
UPDATE product SET title = 'Concept2 Model D PM5 划船机' WHERE id = 88;
UPDATE product SET title = 'Osprey Atmos AG 65 男款登山背包' WHERE id = 89;
UPDATE product SET title = 'PowerBlock Elite EXP 可调节哑铃 5-50磅' WHERE id = 90;
UPDATE product SET title = 'Brooks Ghost 16 缓震跑鞋 男款44码' WHERE id = 91;
UPDATE product SET title = 'Yeti SB140 T3 全避震山地车 L码' WHERE id = 92;
UPDATE product SET title = '佳明 Edge 840 Solar 太阳能码表' WHERE id = 93;
UPDATE product SET title = 'Peak Design 碳纤维旅行三脚架' WHERE id = 94;
UPDATE product SET title = 'Patagonia Black Hole 防水行李袋 55L' WHERE id = 95;
UPDATE product SET title = 'Rapha Pro Team 长袖骑行服 深蓝色L码' WHERE id = 96;
UPDATE product SET title = 'Black Diamond Spot 400-R 头灯' WHERE id = 97;
UPDATE product SET title = 'Shimano Ultegra R8000 公路车套件 11速' WHERE id = 98;
UPDATE product SET title = 'Hydro Flask 宽口保温杯 32oz' WHERE id = 99;
UPDATE product SET title = 'Titleist Pro V1 高尔夫球 3打球装' WHERE id = 100;
UPDATE product SET title = '海蓝之谜 La Mer 经典面霜 60ml' WHERE id = 101;
UPDATE product SET title = 'Tom Ford Oud Wood 乌木沉香 50ml' WHERE id = 102;
UPDATE product SET title = 'Olaplex No.3 头发修复精华 100ml' WHERE id = 103;
UPDATE product SET title = '祖玛珑 英国梨与小苍兰 100ml' WHERE id = 104;
UPDATE product SET title = 'Augustinus Bader 德国AB蓝面霜 50ml' WHERE id = 105;
UPDATE product SET title = 'Byredo Gypsy Water 流浪者之歌 50ml' WHERE id = 106;
UPDATE product SET title = 'Drunk Elephant C-Firma 维C日间精华' WHERE id = 107;
UPDATE product SET title = '伊索 Resurrection 复活芳香护手霜' WHERE id = 108;
UPDATE product SET title = '资生堂 红腰子精华 75ml' WHERE id = 109;
UPDATE product SET title = 'Charlotte Tilbury Pillow Talk 枕边话口红' WHERE id = 110;
UPDATE product SET title = 'Tatcha 水润面霜 50ml' WHERE id = 111;
UPDATE product SET title = 'NARS 光亮柔滑遮瑕膏 Custard色号' WHERE id = 112;
UPDATE product SET title = '蒂普提克 Baies 浆果香氛蜡烛 190g' WHERE id = 113;
UPDATE product SET title = 'Sunday Riley Good Genes 乳酸焕肤精华 30ml' WHERE id = 114;
UPDATE product SET title = 'Clarisonic Mia Smart 超声波洁面仪' WHERE id = 115;
UPDATE product SET title = 'UPPAbaby VISTA V2 高景观婴儿推车 蓝色' WHERE id = 116;
UPDATE product SET title = 'Nuna RAVA 儿童安全座椅 黑色' WHERE id = 117;
UPDATE product SET title = 'BabyBjorn 婴儿摇椅 灰色网面款' WHERE id = 118;
UPDATE product SET title = 'Hatch Rest 婴儿助眠灯 白噪音夜灯' WHERE id = 119;
UPDATE product SET title = 'Lovevery 早教玩具套装 5-6月龄' WHERE id = 120;
UPDATE product SET title = 'Babyzen YOYO2 轻便婴儿推车 6月以上款' WHERE id = 121;
UPDATE product SET title = 'Ergobaby Omni 360 婴儿背带 珍珠灰' WHERE id = 122;
UPDATE product SET title = '4moms mamaRoo 5 多功能婴儿摇椅' WHERE id = 123;
UPDATE product SET title = 'Magna-Tiles 磁性积木 透明色100片装' WHERE id = 124;
UPDATE product SET title = 'Skip Hop 婴儿三阶段活动中心' WHERE id = 125;
UPDATE product SET title = 'Britax B-Safe Gen2 婴儿提篮安全座椅 黑色' WHERE id = 126;
UPDATE product SET title = 'Graco SimpleSwitch 多功能儿童餐椅 白灰色' WHERE id = 127;
UPDATE product SET title = 'Kyte BABY 竹纤维婴儿睡袋 鼠尾草绿' WHERE id = 128;
UPDATE product SET title = 'Melissa & Doug 木质玩具厨房套装' WHERE id = 129;
UPDATE product SET title = '费雪 Kick & Play 钢琴健身毯' WHERE id = 130;
